### PR TITLE
Add French translation

### PR DESCRIPTION
**Pull request by Anne017**
Add French translation

### CODE REVIEW

**Comment by Anne017** [comment]
Hello, could you please take some time to consider my pull request?
I thank you in advance.

**Comment by danjjl** [comment]
Dear Anne,

Sorry for this long overdue answer!

I no longer have access to a smart-phone and in consequence, I do not have an Ubuntu touch phone available.

Before I merge these changes could you confirm the project still builds and installs correctly?

On 10/08/16 21:49, Anne017 wrote:

Hello, could you please take some time to consider my pull request?
I thank you in advance.

**Comment by Anne017** [comment]
Thank you for your answer.
Unfortunately, I have never had a Ubuntu phone to test but since only the .po file has been modified, I guess the project still builds and installs correctly.

**Comment by Anne017** [comment]
Hello! Do you have some time to review this pull request?

**Comment by Bebekoualy** [comment]
I would love to translate your app into French!!

**Pull request closed without merging**
